# Generated by Django 4.2.15 on 2024-08-23 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_customuser_id_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7fb2ec93-bc77-470f-b02f-61f095fef623'), primary_key=True, serialize=False),
        ),
    ]
